name: CI for Ansible Backup Playbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-playbook:
    runs-on: ubuntu-latest

    steps:
      

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i hosts.yaml install.yaml
